logging:
  level:
    root: INFO
    com.westsomsom.finalproject: DEBUG
spring:
  application:
    name: finalproject
  config:
    import:
      - 'aws-parameterstore:/west-somsom/rds/'
      - 'aws-parameterstore:/west-somsom/arn/'
      - 'aws-parameterstore:/west-somsom/redis/'
      - 'aws-parameterstore:/west-somsom/kakao/'
  datasource:
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${DB_URL_REPLICA}
      username: ${DB_NAME}
      password: ${DB_PASSWORD}
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${DB_URL}
      username: ${DB_NAME}
      password: ${DB_PASSWORD}

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  devtools:
    livereload:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      cache:
        store: ${CACHE_STORE}

  profiles:
    include: local

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

custom:
  scheduler:
    targetArn: ${TARGET_ARN}
    roleArn: ${ROLE_ARN}

kakao:
  client:
    id: ${KAKAO_ID}
    secret: ${KAKAO_SECRET}
  redirect:
    url: ${KAKAO_URL}
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always