spring:
  application:
    name: finalproject

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  profiles:
    include: local

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
