logging:
  level:
    root: INFO
    com.westsomsom.finalproject: DEBUG
spring:
  application:
    name: finalproject

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: localhost #${aws.paramstore.west-somsom.redis.host}
      port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  profiles:
    include: local

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true