logging:
  level:
    root: INFO
    com.westsomsom.finalproject: DEBUG
    org.springframework.web.socket: DEBUG  # WebSocket 관련 로그 디버깅

spring:
  application:
    name: finalproject
  config:
    import:
      - 'aws-parameterstore:/west-somsom/rds/'
      - 'aws-parameterstore:/west-somsom/arn/'
      - 'aws-parameterstore:/west-somsom/redis/'
      - 'aws-parameterstore:/west-somsom/kakao/'

  datasource:
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${DB_URL_REPLICA}
      username: ${DB_NAME}
      password: ${DB_PASSWORD}
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${DB_URL}
      username: ${DB_NAME}
      password: ${DB_PASSWORD}

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  devtools:
    livereload:
      enabled: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      timeout: 6000ms  # Redis 응답 타임아웃 설정 (6초)
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5000ms  # 최대 대기 시간 5초

  profiles:
    include: local

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  forward-headers-strategy: framework  # Proxy 환경(WebSocket 포함)에서 헤더 처리

custom:
  scheduler:
    targetArn: ${TARGET_ARN}
    roleArn: ${ROLE_ARN}

kakao:
  client:
    id: ${KAKAO_ID}
    secret: ${KAKAO_SECRET}
  redirect:
    url: ${KAKAO_URL}

management:
  endpoints:
    web:
      exposure:
        include: health

websocket:
  allowed-origin-patterns: "*"  # WebSocket CORS 설정 (Spring Boot 2.4 이상)
  message-buffer-size: 8192  # 메시지 버퍼 크기 (8KB)
  session-timeout: 3600  # WebSocket 세션 유지 시간 (초 단위)