spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

custom:
  scheduler:
    targetArn: ${TARGET_ARN}
    roleArn: ${ROLE_ARN}