spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${DB_URL}
    username: ${DB_NAME}
    url: ${DB_URL}/west_somsom_mysql  # 데이터베이스 이름을 명시적으로 추가
    password: ${DB_PASSWORD}

custom:
  scheduler:
    targetArn: ${TARGET_ARN}
    roleArn: ${ROLE_ARN}